services:
    minecraft-server:
        image: itzg/minecraft-server:${TAG}
        container_name: minecraft-server
        restart: always
        environment:
            EULA: "TRUE"
            TYPE: SPIGOT
            FORCE_GAMEMODE: "TRUE"
            TZ: "${TIMEZONE}"
            VERSION: "${VERSION}"
            SERVER_NAME: "${SERVER_NAME}"
            MOTD: "${MOTD}"
            MAX_PLAYERS: ${MAX_PLAYERS}
            SEED: ${SEED}
            DIFFICULTY: "${DIFFICULTY}"
            MODE: ${MODE}
            ONLINE_MODE: "${ONLINE_MODE}"
            ENFORCE_WHITELIST: "${ENFORCE_WHITELIST}"
            WHITELIST: "${WHITELIST}"
            ENABLE_AUTOPAUSE: "${ENABLE_AUTOPAUSE}"
            SPAWN_PROTECTION: "${SPAWN_PROTECTION}"
            PVP: "${PVP}"
            INIT_MEMORY: "${INIT_MEMORY}"
            MAX_MEMORY: "${MAX_MEMORY}"
        ports:
            - ${BEDROCK_PORT}:19132/udp
            - ${JAVA_PORT}:25565/tcp
        volumes:
            - ./data:/data
        networks:
            - minecraft-network

networks:
    minecraft-network:
        name: minecraft-network
        driver: bridge
